### ISSUE TITLE
Bash requirement on macOS

### ISSUE THREAD

**Issue by sermelipharo** [shinokada/consize#2]
As macOS now defaults to `zsh` due to licensing issues it stores only legacy `bash-3.2` which is checked by the script. 
`Error: This requires Bash v5 or higher. You have version 3.2.57(1)-release.` 
As zsh usually complies with all compatibility requirements with modern `bash`, I guess when runned under `zsh` the script should check `zsh` version instead of `bash`

**Comment by shinokada** [comment]
You can install and run https://github.com/shinokada/macgnu.

**Comment by sermelipharo** [comment]
not really a mandatory. 
I've set `#!/usr/bin/env zsh` and removed bash version check and script works perfectly fine, as I've told macOS built in zsh is fully compatible with modern bash version

**Comment by shinokada** [comment]
I updated it to use zsh.
Please use @v0.7.0.
